### ISSUE TITLE
Make the puppy order factory use google guice

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium#27]
Allow the factory for processing puppy orders to be managed by guice to handle assisted injection.  This will assist with #21

**Comment by satishthulva** [comment]
Hi Symonk, are you talking about OrderProvidable here ? You want an AssistedInject for PuppyOrderFactory ? I'm very sure I'm missing something fundamental here. Please let me know.

**Comment by symonk** [comment]
basically we just need a way for google guice to handle this factory / provider of PuppyOrders, I assume because its returning PuppyOrders by calling `new` on them, then AOP from guice will not apply in those objects, or so it didn't when I was messing around with it.

But i'm quite new to using google guice, if you know it better im completely open for suggestions :)

**Comment by satishthulva** [comment]
As far as I know, as long as there are some **dynamic** parameters( the things that Guice is not managing ) in the object constructor, object creation has to happen through application code itself. This is true with any dependency injection framework in my opinion.

**Comment by satishthulva** [comment]
@symonk : by AOP, do you mean method interception in Guice ?

**Comment by symonk** [comment]
method interception yes.  I want to run some code from implementing a MethodInterceptor on the objects that the PuppyOrderProvider returns, e.g a PuppyOrder but I can't seem to get guice executing the intercepted method code on those Objects

**Comment by symonk** [comment]
lets say we had an annotation @Random that a method of a PuppyOrder contains, i can't intercept methods with this annotation in guice because I don't think guice is handling the instantiation of those PuppyOrder object/beans.

**Comment by satishthulva** [comment]
Okay. Got it. Let me try this.

**Comment by symonk** [comment]
look forward to your approach :) thanks @satishthulva

**Comment by satishthulva** [comment]
@symonk : I created a pull request for this. I did not put a method interceptor and annotation for method interceptor, as I do not know which method in PuppyOrder we're supposed to intercept and what the interceptor should do. But, I tested it on a sample project I created. Please take a look at [GuiceAssistedAOP](https://github.com/satishthulva/GuiceAssistedAOP)

One more thing, I do not know what is Allure so what the Allure call doing too in PuppyOrder call. If it is needed, please add it in the PuppyOrder constructor.

**Comment by symonk** [comment]
yep we just want to serialize and attach to allure on POST construct basically.  I will pull down your fork and have a look now :)

**Comment by symonk** [comment]
Great work @satishthulva I haven't had more time to fully investigate but it looks like a great start
