### ISSUE TITLE
Implement an annotation for @Notify

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium#29]
This annotation will parse to the configured output channel and log any tests marked with this annotation to ping either the slack or hipchat API to deliver a notification on its status

**Comment by chikaslocalhost** [comment]
I'll look on this issue

**Comment by symonk** [comment]
thanks @chikaslocalhost right now only slack is built in functionality, so focusing there is a good start. there is a pending issue for adding hipchat support which I will build in later
