### ISSUE TITLE
Add hipchat support

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium#30]
-> Add properties for hipchat api client / token
-> Implement strategy pattern for hipchat/slack into a communications medium, right now we only support slack but lets add hipchat in and give the user(s) an easy means of configuring which one they want to use.

A) Create notifications.props in /resources?
B) Add some to .properties and parse/use those using Owner

**Comment by sebastiaanspeck** [comment]
Need help for this?

**Comment by symonk** [comment]
sure thing @sebastiaanspeck I assume there is a simple library already in existence that we can incorporate, but we will need to rewrite some communication code to use something like strategy pattern when we add more than slack

**Comment by sebastiaanspeck** [comment]
Where can I find the communication code?
